---
title: "SDV Benchmark"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
source("generative_ranger.R")
```

```{python, include=FALSE}
import numpy as np
import sdgym
from sdgym.synthesizers import Independent, Identity, CTGAN 
```

```{r, include=FALSE}
my_generative_ranger <- function(x) {
  x_r <- py_to_r(x)
  
  # Chars and logicals to factors
  idx_char <- sapply(x_r, is.character)
  x_r[idx_char] <- as.data.frame(lapply(x_r[idx_char], as.factor))
  idx_logical <- sapply(x_r, is.logical)
  x_r[idx_logical] <- as.data.frame(lapply(x_r[idx_logical], as.factor))
  
  # Run generative RF
  res <- generative_ranger(x_real = x_r, x_synth = NULL, n_new = nrow(x_r),
                           num.trees = 10, min.node.size = 50)
  
  # Convert logicals back
  if (any(idx_logical)) {
    res[idx_logical] <- as.data.frame(lapply(res[idx_logical], function(x) {x == "TRUE"}))
  }
  
   # Convert chars back
  if (any(idx_char)) {
    res[idx_char] <- as.data.frame(lapply(res[idx_char], as.character))
  }
  
  # Round integers
  check.integer <- function(x) {
    is.numeric(x) && all(x == as.integer(x))
  }
  idx_int <- sapply(py_to_r(x), check.integer)
  if (any(idx_int)) {
    res[idx_int] <- as.data.frame(lapply(res[idx_int], round))
    res[idx_int] <- as.data.frame(lapply(res[idx_int], as.integer))
  }
  
  # Return synthetic data
  colnames(res) <- colnames(x_r)
  res
}
```

# Run benchmark in python
```{python}
def gen_rf(real_data, metadata):
    table_name = metadata.get_tables()[0]
    return {table_name: r.my_generative_ranger(real_data[table_name])}

synthesizers = [Identity, CTGAN, gen_rf] # Identity should return original data as synthetic data
#scores = sdgym.run(synthesizers=synthesizers, datasets=['adult', 'census', 'intrusion', 'news'])
scores = sdgym.run(synthesizers=synthesizers, datasets=['adult'])
```

# Show results from python
```{python, eval = FALSE}
#pd.set_option('display.max_columns', 20) 
scores
```
# Show results from R
```{r}
library(data.table)
scores <- data.table(py$scores)
scores
#scores[, mean(score), by = synthesizer]
```



